### PR TITLE
Add guide to reporting bugs to contributions.md

### PR DESCRIPTION
**Pull request by Midnite**
Could change that one link in case we'd rather track issues in Trello or somewhere else instead of github issues.

### CODE REVIEW

**Comment by robbiemccorkell** [comment]
That `package-lock` file will have come from an `npm install`. If you delete it, and install dependencies with yarn in the future it won't appear.

**Comment by Midnite** [comment]
@robbiemccorkell Oops, didn't notice that, deleted.

**Comment by frigus02** [comment]
Nice work with the issue template. :+1:

The markdown headlines are a bit messed up. But instead of fixing this, maybe we want to extract this into a file `.github/ISSUE_TEMPLATE.md`. This way users will see it when they create a new issue.

**Comment by Midnite** [comment]
@frigus02 good idea! will do it tomorrow

**Comment by x4d3** [comment]
@frigus02 I've applied the requested change. (fyi @Midnite )

**Pull request merged**
