### PR TITLE
New app icon

### PR DESCRIPTION
**Pull request by frigus02**
## Tester check-list

* [ ] Tested on multiple devices / OS versions (Test on the physical device(s) you have access to, otherwise use BrowserStack):

  * [x] Galaxy S8 (Android 7.0/8.0)
  * [x] Galaxy S7 (Android 6.0)
  * [x] iPhone X (iOS 11.x)
  * [x] iPhone 8 (11.x)
  * [ ] iPhone 7 (iOS 10.x)

  Optional:

  * [ ] Google Pixel 2
  * [ ] Galaxy S8 Plus
  * [ ] Galaxy S7 Edge
  * [ ] Galaxy S6
  * [x] iPhone 7+
  * [ ] iPhone 6

### CODE REVIEW

**Comment by frigus02** [comment]
I used the [Icon Set Creator](https://itunes.apple.com/de/app/icon-set-creator/id939343785?l=en&mt=12) to create the different sizes for iOS. I noticed that it generated fewer icons that we had previously. @markholland, I think you added the icons originally. Which tool did you use to generate the different sizes?

**Comment by markholland** [comment]
https://makeappicon.com/

**Comment by frigus02** [comment]
Perfect, thanks. Now we have the same amount icon sizes 👍

**Comment by declanslevin** [comment]
Looks good on both iOS and Android

**Pull request merged**
