### PR TITLE
Switch dates if end date is before start date

### PR DESCRIPTION
**Pull request by jonyardley**
As there is no validation in contentful if the `startTime` is after the `endTime` then we should switch them around as to not break elements in the UI.

I have also moved the locale into a separate module. (Probably should have done this in a separate PR but thought some housekeeping wouldn't go amiss).

Fixes: #73

## Pre-flight check-list
* [x] Documentation (N/A)
* [x] Unit tests

## Pre-merge check-list

* [ ] Tester approved

## TestPlan
- [ ] Create/change an event in contentful with the start date before the end date.
- [ ] App does not break and start and end date should be switched.

### CODE REVIEW

**Comment by jonyardley** [comment]
@declanslevin I have moved this onto a new branch in favour of the old one to potentially fix a bad rebase. I have also increased the timeout for the ios-e2e which was failing.

**Comment by jonyardley** [comment]
This is green now :)

**Comment by declanslevin** [comment]
So this is working when I build the app locally (Android) by pulling the branch, but if I download the latest hockeyapp builds (alpha or beta) the dates aren't being corrected. It was working earlier (on both Android and iOS) when testing the hockeyapp builds, so it seems like maybe later commits are conflicting with the changes committed for this branch?

**Comment by jonyardley** [comment]
hmm weird. Just done a merged from master. Maybe that will help?

**Comment by declanslevin** [comment]
I think I just didn't understand completely how hockeyapp builds work... after some fiddling and help from Jan we figured it out.

Tested on:
(Physical)
Galaxy S8
iPhone 7+ 

(BrowserStack)
Galaxy S7

And it's working correctly (and the date filter crash is gone too)

Pending testing on some other iOS devices (once I can get the proper build from hockeyapp)

**Pull request merged**
