### PR TITLE
Update react-native-maps

### LINKED ISSUE #89: Debugger enabled crashes android app because of outdated dependency
Reproduction

1. `yarn run-android`
2. `cmd+m` in the emulator
3. Enable remote js debugging
4. Visit `http://localhost:8081/debugger-ui/` 
5. Confirm that the app connects to the debugger then immediately crashes.

Logs

```
04-04 10:16:51.374 10541 10580 E AndroidRuntime: FATAL EXCEPTION: mqt_js
04-04 10:16:51.374 10541 10580 E AndroidRuntime: Process: com.pridelondonapp.dev, PID: 10541
04-04 10:16:51.374 10541 10580 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getOpenSourceSoftwareLicenseInfo(Landroid/content/Context;)Ljava/lang/String; in class Lcom/google/android/gms/common/GoogleApiAvailability; or its super classes (declaration of 'com.google.android.gms.common.GoogleApiAvailability' appears in /data/app/com.pridelondonapp.dev-1/base.apk)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapModule.getConstants(AirMapModule.java:50)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:140)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
04-04 10:16:51.374 10541 10580 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
04-04 10:16:51.375 12813 13249 W ActivityManager:   Force finishing activity com.pridelondonapp.dev/com.pridelondonapp.MainActivity
```

[This issue](https://github.com/react-community/react-native-maps/issues/1571) seems to be the cause. Updating react-native-maps to the latest solves the problem. PR is coming soon.

### PR DESCRIPTION
**Pull request by daralthus**
Updates dependency to fix crashing debugger issue on android. Closes #89 

## Pre-flight check-list

Before raising a pull request

* [x] Documentation
* [x] Unit tests

## Pre-merge check-list

* [ ] Tester approved

### CODE REVIEW

**Comment by robbiemccorkell** [comment]
I actually used the ignite CLI to install it, and then removed the ignite config: https://github.com/infinitered/ignite-maps

The advantage was that I didn't have to worry about committing cocoapods code, or adding it as an extra build step. The disadvantage is that iOS users are stuck with using Apple Maps (which might not be a problem) because cocoapods installs the google sdk for iOS.

**Comment by markholland** [comment]
Right, so that's why simply bumping the version in npm won't work. Might have to go the CocoaPods route as the react-native-maps version is harcoded in ignite and I doubt all that's needed is to increase that 😬. I'll try it though.

**Comment by daralthus** [comment]
So there is a hackish workaround described here https://github.com/react-community/react-native-maps/issues/2159 but I am not too keen on going down that road. @robbiemccorkell What was the reasoning not to use cocoapods?

Alternatively there's always Mapbox :P

**Comment by robbiemccorkell** [comment]
The only reason I didn't use cocoapods is that the cocoapods install downloads _a lot_ of stuff into the repo. So either that would all have to be committed in, or a cocoapods install step would be need to be added to our CI build config.

Since using Google Maps in iOS wasn't an explicit requirement I skipped it.

I think the install process for react-native-maps is exactly the same otherwise. The things that ignite did were basically the same as the manual installation guide provided by react-native-maps, just skipping the iOS cocoapods step.

I think it should be possible to update everything ok without ignite. Otherwise cocoapods certainly isn't a disaster.

My original commit introducing maps is here: https://github.com/redbadger/pride-london-app/commit/5356158da37520eeb423f277bc636e843b554091

Might be worth looking at the manual install guide in relation to this commit and seeing where they line up.

**Comment by markholland** [comment]
Is this still relevant?

**Comment by markholland** [comment]
[See](https://github.com/redbadger/pride-london-app/issues/89#issuecomment-389877870)

**Pull request closed without merging**
